[workspace]
authors = ["Tarik Hrnjica <tarik.hrnjica@gmail.com>"]
channels = ["conda-forge"]
name = "c-star"
platforms = ["osx-arm64"]
version = "0.1.0"

[environments]
default = ["dev"]

[tasks]
license = "licenseheaders -t HEADER -d cstar/ -x '**/__init__.py'"

[dependencies]
ruff = ">=0.14.14,<0.15"

[pypi-dependencies]
numpy = ">=2.4.2, <3"

[feature.dev.pypi-dependencies]
licenseheaders = "*"
